#!/bin/sh

# shellcheck disable=SC1091
. /usr/libexec/os-helpers-logging

rollback_fixup_enabled() {
    if [ "$bootparam_balena_stage2" != "true" ]; then
        return 1
    fi

    if [ "${IS_ROLLBACK}" != "1" ]; then
        return 1
    fi

    return 0
}

rollback_fixup_run() {
    OLDROOT_MOUNT="/oldrootfs"
    BOOTDEV="mmcblk2boot0"

    UBOOT_FILE="imx-boot-iot-gate-imx8-sd.bin-flash_evk"

    # Check whether the old system does not use balena bootloader
    mkdir -p "${OLDROOT_MOUNT}"
    alt_root_part="B"
    if [ "${ROOT_PART}" = "${alt_root_part}" ]; then
        alt_root_part="A"
    fi
    mount "/dev/disk/by-label/resin-root${alt_root_part}" "${OLDROOT_MOUNT}"
    if find "${OLDROOT_MOUNT}" -type f -name "$(basename ${BOOTENV_FILE})" | grep -q .; then
        # Balena bootloader is in use, no extra actions needed
        umount "${OLDROOT_MOUNT}"
        return 0
    fi

    # Re-program the old U-boot to bypass balena bootloader as the old kernel
    # might not be able to kexec without patches.
    warn "Rolling back U-boot"
    echo 0 > "/sys/block/${BOOTDEV}/force_ro"
    if ! dd if="${OLDROOT_MOUNT}/boot/${UBOOT_FILE}" of="/dev/${BOOTDEV}" conv=fsync bs=1024; then
        error "Failed to roll back U-boot - system probably won't boot"
    fi
    echo 1 > "/sys/block/${BOOTDEV}/force_ro"

    # Configure the old u-boot to perform altboot to restore boot partition contents
    # Set `resin_root_part` to the partition that failed to boot
    blockdev=$(lsblk -nlo name "/dev/disk/by-label/resin-root${ROOT_PART}")
    new_part_idx=$(cat "/sys/class/block/$blockdev/partition")
    new_part_idx=$(printf "%x" $new_part_idx)
    info "Setting uboot root partition index to $new_part_idx..."
    tmpfile="$(mktemp)"
    echo "resin_root_part=$new_part_idx" > ${tmpfile}
    echo "upgrade_available=${UPGRADE_AVAILABLE}" >> ${tmpfile}
    mv "${tmpfile}" "${BOOT_MOUNT}/resinOS_uEnv.txt"

    # And set maximum boot count reached OS_BOOTCOUNT_LIMIT so U-boot will altboot
    echo "bootcount=3" > ${tmpfile}
    rm -f "${BOOT_MOUNT}"/*bootcount.env* || true
    mv "${tmpfile}" "${BOOT_MOUNT}/bootcount.env"
    rm -f "${BOOT_MOUNT}/bootenv"

    # Reboot into the old u-boot
    info "Rebooting into rolled back U-boot"
    umount "${OLDROOT_MOUNT}"
    umount "${BOOT_MOUNT}"
    reboot -f
}
