#!/bin/bash

GV='/sys/devices/system/cpu/cpu0/cpufreq'
echo userspace > ${GV}/scaling_governor

sleep 5

while [ 1 ];do
    for gov in $(cat ${GV}/scaling_available_frequencies);do
        echo $gov > ${GV}/scaling_setspeed
        sleep 3
    done
done
